# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Install .NET Core SDK"
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    publishTestResults: true
    arguments: '--collect "Code coverage"'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Publishing the binaries"
      Write-Host "Binaries folder is $(Build.BinariesDirectory)"
      
      Rename-Item -Path "$(Build.BinariesDirectory)\bin\Debug\net6.0" -NewName "AzureVmCalc"
      
      dir "$(Build.BinariesDirectory)\bin\Debug\AzureVmCalc"
    pwsh: true
